PlasmoHQ/plasmo

cli/plasmo/src/features/extension-devtools/package-file.ts

1. run `pnpm dlx plasmo init example-dir`
2. `.prettierrc.cjs` has require `@trivago/prettier-plugin-sort-imports` , but not in `package.json`

fix: missing dep @trivago/prettier-plugin-sort-imports

---

cli/create-plasmo/package.json
cli/plasmo/package.json
packages/parcel-config/package.json
packages/parcel-runtime/loaders/hmr-runtime.js
packages/parcel-runtime/package.json
pnpm-lock.yaml

Closes https://discord.com/channels/946290204443025438/983397810533720075/994962911699161180.
After restarting `plasmo dev`, I have to manually reload my extension (from `chrome://extensions`) for HMR to work - this is because after the `hmr-runtime` WebSocket connection is lost, it never attempts to reconnect. 
This PR adds [`reconnecting-websocket`](https://github.com/pladaria/reconnecting-websocket).

feat(parcel-runtime): HMR Reconnect

---

cli/plasmo/src/features/manifest-factory/create-manifest.ts

Context: https://discord.com/channels/946290204443025438/978320682985349130/1015413639827705906
I only tested newtab.tsx, I'm going to assume the underlying `initTemplateFile` function works as expected
with newtab.tsx:
```
➜  with-newtab git:(8fa7fff) pnpm run build   
> with-newtab@0.0.0 build plasmo/examples/with-newtab
> plasmo build
🟣 Plasmo v0.52.5
🟠 The browser extension development framework.
🔵 INFO   | Prepare to bundle the extension...
🟢 DONE   | Finished in 2380ms!
```
after removing newtab.tsx:
```
➜  with-newtab git:(8fa7fff) pnpm run build
> with-newtab@0.0.0 build plasmo/examples/with-newtab
> plasmo build
🟣 Plasmo v0.52.5
🟠 The browser extension development framework.
🔵 INFO   | Prepare to bundle the extension...
🟠 WARN   | Unable to find any entrypoints. You may end up …
```

feat: add a warning message if there are no entrypoints

---

cli/plasmo/src/features/extension-devtools/generate-icons.ts
cli/plasmo/src/features/extension-devtools/project-watcher.ts
cli/plasmo/src/features/helpers/crypto.ts
cli/plasmo/src/features/manifest-factory/base.ts
cli/plasmo/src/features/manifest-factory/mv2.ts
cli/plasmo/src/features/manifest-factory/mv3.ts

feat: improve icon generator, use icon*.NODE_ENV.png

---

cli/plasmo/src/commands/build.ts
cli/plasmo/src/commands/dev.ts

feat: adding --source-maps flag for production

---

packages/init/templates/README.md

When I tried initializing my project, I noticed that the current link to the docs webpage, for submitting to the web   store, doesn't seem to work.  Specifically, the anchor doesn't seem to jump to any specific content on https://docs.plasmo.com/workflows.  I figured the following link is the right one.
https://docs.plasmo.com/workflows/submit

doc: update hyperlink for submission

---

cli/create-plasmo/package.json
cli/plasmo/package.json
cli/plasmo/src/commands/build.ts
cli/plasmo/src/commands/dev.ts
cli/plasmo/src/features/extension-devtools/generate-icons.ts
cli/plasmo/src/features/extension-devtools/load-env-config.ts
cli/plasmo/src/features/extension-devtools/package-file.ts
cli/plasmo/src/features/extension-devtools/project-path.ts
cli/plasmo/src/features/extra/next-new-tab.ts
cli/plasmo/src/features/helpers/package-manager.ts
cli/plasmo/src/features/helpers/traverse.ts
cli/plasmo/src/features/manifest-factory/base.ts
cli/plasmo/src/features/manifest-factory/mv2.ts
cli/plasmo/src/features/manifest-factory/mv3.ts
cli/plasmo/src/features/manifest-factory/scaffolder.ts
cli/plasmo/src/features/manifest-factory/ui-library.ts
cli/plasmo/src/features/project-creator/from-existing-manifest.ts
cli/plasmo/src/features/project-creator/git-init.ts
cli/plasmo/src/features/project-creator/index.ts
cli/plasmo/src/features/project-creator/install-dependencies.ts
cli/plasmo/src/index.ts
cli/plasmo/templates/static/vanilla/index.html
cli/plasmo/templates/static/vanilla/index.ts

feat: Make UI library optional

---

cli/create-plasmo/package.json
cli/plasmo/index.d.ts
cli/plasmo/package.json
cli/plasmo/src/features/extension-devtools/common-path.ts
packages/parcel-config/package.json
packages/parcel-resolver/package.json
packages/parcel-resolver/src/handle-remote-caching.ts
packages/parcel-resolver/src/shared.ts
packages/parcel-transformer-manifest/package.json
packages/parcel-transformer-manifest/src/state.ts

_Quick note: Giving `plasmo` another go - having a great experience so far!_
I've added environment variable `PLASMO_SRC_PATH` to override `"src"` so we can put all of our Plasmo entry points (ie. `content.ts`/`background.ts`) inside `./src/extension` instead of cluttering the `./src` directory.
Alternative options:
- adding command line option `plasmo dev --src-dir src/extension`
- adding `plasmo.config.js`:
```js
// plasmo.config.js
const path = require('path');
module.exports = { 
sourceDirectory: path.resolve(process.cwd(), 'src/extension') 
}
```
This would be a real QOL upgrade for us. I appreciate this is a quick 'n' easy hack but would be grateful for the merge now & replace whith a better solution down the line.

feat: add PLASMO_SRC_PATH and --src-path

---

cli/create-plasmo/package.json
cli/plasmo/package.json
cli/plasmo/src/commands/dev.ts
packages/parcel-config/index.json
packages/parcel-config/package.json
packages/parcel-resolver-post/.gitignore
packages/parcel-resolver-post/package.json
packages/parcel-resolver-post/src/handle-ts-path.ts
packages/parcel-resolver-post/src/index.ts
packages/parcel-resolver-post/src/shared.ts
packages/parcel-resolver-post/src/utils.ts
packages/parcel-resolver-post/tsconfig.json
packages/parcel-resolver/src/handle-tilde-src.ts
packages/parcel-resolver/src/shared.ts
packages/parcel-runtime/package.json
packages/parcel-runtime/src/index.ts
pnpm-lock.yaml

Add support for `paths` in `tsconfig.json` in Parcel 2.
Parcel issue: https://github.com/parcel-bundler/parcel/issues/4936
Resolution: https://github.com/zachbryant/parcel-resolver-tspaths

feat: support tsconfig paths

---

cli/plasmo/src/commands/build.ts
cli/plasmo/src/commands/package.ts
cli/plasmo/src/features/manifest-factory/zip.ts

feat: adding package cmd

---

packages/parcel-transformer-manifest/package.json
packages/parcel-transformer-manifest/src/schema.ts
packages/parcel-transformer-manifest/src/validate-version.ts

As per the following docs, the version specified in the manifest can have up to 4 integers (separated by dots).
https://developer.chrome.com/docs/extensions/mv3/manifest/version/
https://developer.chrome.com/docs/extensions/mv3/manifest/minimum_chrome_version/
The schema currently only allows up to 3, so I updated the validation logic to allow up to 4.

fix: allow up to 4 integers in version

---

cli/plasmo/src/features/extension-devtools/project-path.ts
cli/plasmo/src/features/manifest-factory/base.ts
cli/plasmo/src/features/manifest-factory/ui-library.ts

feat: supports js extension for react and vanilla ui

---

packages/parcel-optimizer-terser/tsup.config.ts
packages/parcel-resolver/package.json
packages/parcel-resolver/src/polyfills/assert.ts
packages/parcel-resolver/src/polyfills/buffer.ts
packages/parcel-resolver/src/polyfills/console.ts
packages/parcel-resolver/src/polyfills/crypto.ts
packages/parcel-resolver/src/polyfills/domain.ts
packages/parcel-resolver/src/polyfills/events.ts
packages/parcel-resolver/src/polyfills/http.ts
packages/parcel-resolver/src/polyfills/https.ts
packages/parcel-resolver/src/polyfills/os.ts
packages/parcel-resolver/src/polyfills/path.ts
packages/parcel-resolver/src/polyfills/process.ts
packages/parcel-resolver/src/polyfills/punycode.ts
packages/parcel-resolver/src/polyfills/querystring.ts
packages/parcel-resolver/src/polyfills/stream.ts
packages/parcel-resolver/src/polyfills/string_decoder.ts
packages/parcel-resolver/src/polyfills/sys.ts
packages/parcel-resolver/src/polyfills/timers.ts
packages/parcel-resolver/src/polyfills/tty.ts
packages/parcel-resolver/src/polyfills/url.ts
packages/parcel-resolver/src/polyfills/util.ts
packages/parcel-resolver/src/polyfills/vm.ts
packages/parcel-resolver/src/polyfills/zlib.ts

This PR fix the export for nodejs browserified polyfill.
Most module that consumes these polyfill do it like this:
```
import Buffer from "buffer"
```
However, our `export *` strategy doesn't have a `default` export, causing issue for downstream user and peer dependency

fix: polyfill export signature

---

cli/plasmo/package.json
cli/plasmo/src/features/extension-devtools/build-watcher.ts
cli/plasmo/src/features/manifest-factory/base.ts
pnpm-lock.yaml

Ref: https://discord.com/channels/946290204443025438/1059356193983840256

hotfix: sharp library version

---

cli/create-plasmo/package.json
cli/plasmo/package.json
packages/parcel-config/package.json
packages/parcel-resolver/index.mjs
packages/parcel-resolver/package.json
packages/parcel-resolver/src/handle-alias.ts
packages/parcel-resolver/src/handle-module-exports.ts
packages/parcel-resolver/src/index.ts
packages/parcel-resolver/src/shared.ts
pnpm-lock.yaml

This PR parse the alias list upfront in our custom resolver and short-circuit the parcel resolver default polyfill. This allows us to easily patch packages via alias, with TS!
It also bypass the ESM resolver on Parcel'end with the node resolver, allow known ESM module to just work.

feat: prioritize local alias resolution above polyfill

---

cli/plasmo/src/features/project-creator/index.ts

-  Minor typo fix on CLI's `Author Name` prompt

fix(cli): typo on cli author name prompt

---

packages/parcel-runtime/src/utils/loading-indicator.ts

The event might've already fired before we subscribed to it, so lets check if `document.documentElement` already exists.

fix(parcel-runtime): Inject loader only if document element exists

---

packages/parcel-runtime/src/utils/loading-indicator.ts

The loading indicator element defined a "hidden" CSS class that didn't work well with libraries like tailwind, breaking the plasma website among others when developing locally. The issue was described in #499.
In this PR, I added the `LOADING_ID` as a prefix to all the styles so that there is no conflict between the class names.

fix: loading indicator styles clashing with the commonly used 'hidden' class

---

cli/create-plasmo/package.json
cli/plasmo/package.json
packages/parcel-config/package.json
packages/parcel-resolver-post/package.json
packages/parcel-resolver-post/src/handle-ts-path.ts

This PR adds support for finding tsconfig paths from tsconfigs that use `extends`.
I originally posted in discord asking if it was possible to use plasmo in an nx monorepo (https://discord.com/channels/946290204443025438/1088301075871830067). It didn't seem to be possible, but after looking at the code a bit I thought it might not be too hard to add support. This PR is an initial attempt at that.
I haven't done any testing beyond my use case, so this PR is - at least currently - just asking "is this something you would be interested in supporting?" and not "I'm confident these changes are good".
For a quick tl;dr of my changes: I updated the way paths from tsconfig files were being loaded to recursively follow parent configs specified by `extends`. Additionally, I updated the way …

feat: Support paths in nested (extends) tsconfigs

---

cli/plasmo/templates/static/common/react.ts
cli/plasmo/templates/static/react17/content-script-ui-mount.tsx
cli/plasmo/templates/static/react17/index.tsx
cli/plasmo/templates/static/react18/content-script-ui-mount.tsx
cli/plasmo/templates/static/react18/index.tsx

This PR introduces a new `getGlobalProvider` function for React runtime. This function is aliased with `Layout` to align with some convention from other framework. Thus, user can either do as the RFC described, or this:
```
export const Layout = () => // return a provider here
```
or
```
export const Layout = Provider
```

feat: Layout or globalProvider for React runtime

---

cli/plasmo/templates/static/react17/content-script-ui-mount.tsx
cli/plasmo/templates/static/react18/content-script-ui-mount.tsx

This PR fixes React component keys in an array in templates - moved them to the outermost component.

fix: React templates overlay list array keys fix

---

cli/plasmo/src/features/manifest-factory/base.ts

This PR implements #613, allowing for content scripts to be defined via `index.ts` files within the `contents` directory - for example:
```
src
└── contents
├── another-valid-script
│   ├── utils.ts
│   └── index.tsx
└── valid-script.ts
```
See the original issue for more context / how this mirrors existing functionality.
My current approach is fairly straightforward - in addition to shallowly scanning for files within `contents`, `addContentScriptsNestedDirectories` now handles also scanning shallow directories for any index-like files within them. From what I can tell, simply calling `toggleContentScript` on these nested files behaves as expected and registers the scripts 🎉 
A few other things I tested (though please double check me!):
- dev file watching works as expected, including …

feat: multiple content scripts with index files

---

cli/plasmo/src/features/extension-devtools/package-file.ts
cli/plasmo/src/features/extension-devtools/project-path.ts
cli/plasmo/src/features/extension-devtools/project-watcher.ts
cli/plasmo/src/features/manifest-factory/base.ts
cli/plasmo/src/features/manifest-factory/create-manifest.ts
cli/plasmo/src/features/manifest-factory/mv2.ts
cli/plasmo/src/features/manifest-factory/mv3.ts
cli/plasmo/src/features/manifest-factory/scaffolder.ts
cli/plasmo/src/features/project-creator/index.ts
core/parcel-transformer-manifest/src/handle-deep-loc.ts
pnpm-lock.yaml

This PR aligns the sidepanel API on chrome and the sidebar_action API on firefox

feat: sidepanel API

---

cli/plasmo/src/type.ts
cli/plasmo/templates/static/common/csui.ts
cli/plasmo/templates/static/vue3/content-script-ui-mount.ts
core/parcel-config/index.json
core/parcel-transformer-vue/src/index.ts

https://github.com/PlasmoHQ/plasmo/issues/675
when using vue...
* Import the raw Sfc style string and define `getSfcStyleContent` in `content-script-ui-mount.ts`
* Add `sfcStyleContent` to the `getStyle` argument and pass the result of `getSfcStyleContent` at call time.
* Define getStyle to inject sfc style when getStyle is not defined
* chore: No error if plasmo object is not exported
Note: `getSfcStyleContent` is not intended to be defined by the user.

feat: Inject sfc style to csui root when using vue(#675)

---

.gitignore
cli/create-plasmo/package.json
cli/plasmo/package.json
cli/plasmo/templates/static/common/vue.ts
cli/plasmo/templates/static/vue3/content-script-ui-mount.ts
cli/plasmo/templates/static/vue3/index.ts

Vue is ouputting the following error in console:
```
__VUE_OPTIONS_API__, __VUE_PROD_DEVTOOLS__ are not explicitly defined. You are running the esm-bundler build of Vue, which expects these compile-time feature flags to be globally injected via the bundler config in order to get better tree-shaking in the production bundle.
For more details, see https://link.vuejs.org/feature-flags.
```
This is fixable by assigning a boolean value to each of these global variables but it needs to be done before `createApp()` is called. There is no configuration option in Parcel to handle this so I assigned values to these variables in the Vue3 static template file (cli/plasmo/templates/static/vue3/index.ts).
- (OPTIONAL) Discord ID: dino_morrison
If your PR is accepted, we will award you with the …

bug: Vue throwing warning in console because  __VUE_OPTIONS_API__ and __VUE_PROD_DEVTOOLS__ are not definede

---

cli/plasmo/src/commands/dev.ts

This PR exposes the host options for the development server (via --serve-host) and the hot module reload (via --hmr-host).
We would like these options exposed because our local development environment runs from inside a Docker container. We need a way to expose the development server and HMR that's running inside the Docker container to the local machine to make the development environment work properly.
- (OPTIONAL) Discord ID: N/A

Add serve host and hmr host options to the development script

---

core/parcel-optimizer-es/src/index.ts

The current included version of `@swc/core` changed the default behavior of comment preservation when minifying code. This change explicitly sets the choice to maintain consistent results in compiled scripts.
- (OPTIONAL) Discord ID: `filthytone`

fix: Explicitly set comment preservation option when building

---

core/parcel-runtime/src/utils/0-patch-module.ts
core/parcel-runtime/src/utils/inject-socket.ts

In two previous PRs, support for changing the HMR host and serve host were added:
https://github.com/PlasmoHQ/plasmo/pull/745
https://github.com/PlasmoHQ/plasmo/commit/fa6045e352df956a95ae56e683bcc4ddf2c00c47
Unfortunately, the HMR was still not working when binding to 0.0.0.0. After some exploration, one culprit is that the content script UI isn't successfully connecting to the HMR server. The function it was using to get the hostname of the HMR server would return the location's hostname where the content script was opened on. This PR adds a new function that ensures when fetching the hostname for a socket, it returns "localhost" by default instead of the location's hostname.
I've tested this method of getting the hostname for the socket connection is working in content script UIs and …

Switch inject-socket to use getSocketHostname

---

cli/plasmo/src/type.ts
cli/plasmo/templates/static/common/csui.ts

This PR adds the ability to set the insert position for the inline anchor

feat: Add position option for inline insertion

---

api/messaging/src/index.ts
api/messaging/src/utils.ts

This error message when trying to send a message when there are no active tabs (for example when you're on a `chrome://` page) is a bit cryptic at the moment (`Cannot find property id of undefined`). This PR throws a more explicit error instead.
- Discord ID: 380325824286687233

feat(messaging): More explicit error message when no active tabs

---

api/messaging/src/index.ts
api/messaging/src/types.ts
cli/plasmo/src/features/background-service-worker/bgsw-messaging.ts

This PR ...
Allows usage of the message API when the content script is in the main world. 
To send messages from content scripts in the main world chrome requires the following: 
- The extension's id to be passed as a string to sendMessage()
- The service worker's listener to use onMessageExternal() instead of onMessage()
<a href="https://developer.chrome.com/docs/extensions/mv3/messaging/#external-webpage" target="_blank">Read details from chrome here</a>
[I also submitted a PR to the docs that explains this change](https://github.com/PlasmoHQ/docs/pull/88)
This is my first proper PR to open source so please be kind ❤️

feat: support for messaging from main world content scripts

---

cli/create-plasmo/package.json
cli/plasmo/package.json
core/parcel-config/package.json
core/parcel-runtime/package.json
core/parcel-runtime/src/utils/hmr-utils.ts
pnpm-lock.yaml

- This PR closes #802 
- Also pinned js-transformer to 2.8.3 for #786 

fix: Remove all eval for HMR

---

api/messaging/src/index.ts
api/messaging/src/message.ts

This PR fixes an issue where async listeners would not work:
CS:
```js
listen(async (req, res) => {
if (req.name === "getTabURL") {
await timeout(1000)
res.send(location.href)
return
} else {
res.send("ERROR")
}
})
```
BGSW:
```js
await sendToContentScript({ name: "getTabURL" }) // will return undefined
```
See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#sending_an_asynchronous_response_using_sendresponse

Messaging: Fix async listeners

---

cli/plasmo/src/features/manifest-factory/base.ts
core/parcel-runtime/src/index.ts

React is detected by looking for a react devDependency or dependency. NPM Workspaces (mono repos) do not define these in the project package.json. The mono repo will fail if they are defined. The mono repo root has the dependencies listed.
When looking for React in this type of environment, the peerDependencies should be inspected instead.
- Discord ID: deavial

Allow React to be detected in NPM Workspaces

---

api/messaging/src/utils.ts

This PR will move the `extRuntime` into `getExtRuntime`. Because when the user has not installed the extension and the installation is completed, `extRuntime` already exists. However, the current `extRuntime` still an undefined value, and it is impossible to judge whether the installation is completed based on this.
After modification, `extRuntime` can be obtained in real time.
- Discord ID: crazyurus

feat: move the extRuntime into getExtRuntime

---

cli/plasmo/src/type.ts
cli/plasmo/templates/static/common/csui.ts
cli/plasmo/templates/static/react18/content-script-ui-mount.tsx

This PRs add a proper React's root.unmount() logic so React components destructor will be called as expected

unmount react root

---

cli/plasmo/src/features/extension-devtools/common-path.ts
cli/plasmo/src/features/helpers/create-parcel-bundler.ts

This PR introduces support for a custom `.parcelrc` at the root of the project. It will warn the user if the config doesn't extend Plasmo's one.
This serves as an escape hatch for things like https://github.com/PlasmoHQ/plasmo/issues/521 or https://github.com/PlasmoHQ/plasmo/issues/367.
- Discord ID: 380325824286687233

feat: Support custom .parcelrc config

---

.github/workflows/test-examples.yml
cli/create-plasmo/package.json
cli/plasmo/package.json
cli/plasmo/src/features/background-service-worker/bgsw-messaging.ts
cli/plasmo/src/features/extension-devtools/package-file.ts
package.json

Introduces concept of external messaging handlers. By using the path of `messages/external/`, we can leverage the same messaging features, but they will be registered via `chrome.runtime.onMessageExternal.addListener` instead of `chrome.runtime.onMessage.addListener`.
This fixes an issue currently where all message handlers are being registered as internal AND external handlers, which can be unsafe.
You can either set up a message handler in `background/messages/my-handler.ts` , or `background/messages/external/my-external-handler.ts`. If you want a message handler to work in both contexts, symlink it `ln -s background/messages/my-safe-handler.ts background/messages/external/my-safe-handler.ts`. 
- (OPTIONAL) Discord ID: filthytone
If your PR is accepted, we will award you with the …

feat(external_messaging): Adds external messaging resolver

---

core/parcel-transformer-svelte/src/index.ts

This PR changes the default value of the `css` option in the Svelte transformer to `inject` instead of `external`
When set to `external` the outputted css file is not included in the bundle and never ends being used by content scripts. Setting it to `inject` embeds the css in the bundled js and it ends up being applied in the content scripts.
- (OPTIONAL) Discord ID: 182694885701189639

Fix, default to 'inject' css option  in Svelte transformer

---

cli/plasmo/src/features/background-service-worker/bgsw-messaging.ts

Data is untrusted, so this fixes the case statement to handle a potentially non-existent name field (or undefined/null request data).
- (OPTIONAL) Discord ID: filthytone

fix(external_messaging_name): Fix untrusted external messaging name check

---

core/parcel-compressor-utf8/src/utf8-transform.ts

This PR fixes an issue with parcel-compressor-utf8 with big chunk (that cause Array to throws error). It addresses this issue by creating segment of 1024.
- (OPTIONAL) Discord ID: dp__o

fix(parcel-compressor-utf8): transformChunk with segment size 1024

---

core/parcel-runtime/src/utils/loading-indicator.ts

This PR aimes to fix the issue https://github.com/PlasmoHQ/plasmo/issues/985

Fix CSP Restriction for TrustedTypePolicy Creation in Loading Indicator

---

cli/plasmo/src/features/manifest-factory/base.ts

Allow to configure a hook to be ran whenever a build is made, so that users can perform post-build tasks. This is especially useful for the `dev` task, as a build is ran each time the filetree changes.
This is an opportunity for users to perform custom tasks that they may need on every builds. To do so, they just have to declare a POST_BUILD_SCRIPT environment variable containing the path to a script, like this:
POST_BUILD_SCRIPT=./post-build.cjs plasmo dev
The provided script must export a function, which will be executed:
```javascript
module.exports = function() {
// do stuff after build is done
}
```

feat: add post-build hook

---

core/parcel-runtime/src/utils/loading-indicator.ts

…on in Loading Indicator
This PR aims to fix the issue https://github.com/PlasmoHQ/plasmo/issues/985
The previous issue is exist on website like linkedin.com, I try to fix it
- [ √] I agree to follow this project's [Code of Conduct](https://github.com/PlasmoHQ/plasmo/blob/main/.github/CODE_OF_CONDUCT.md)
- [√ ] I agree to license this contribution under the MIT LICENSE
- [ √] I checked the [current PR](https://github.com/PlasmoHQ/plasmo/pulls) for duplication.

fix: Improved bugfix for CSP Restriction for TrustedTypePolicy Creation in Loading Indicator

---

cli/plasmo/src/features/helpers/flag.ts

The `plasmo build` CLI supports a `--zip` flag which builds your extension and then packages it into a ZIP file.
This is mentioned in the Plasmo docs, but not in the in-CLI help, which I found confusing.
This adds it to the help output, in the process splitting the documentation for the `dev` and `build` commands.

fix(docs): document the `--zip` flag in the `plasmo build` CLI

---

cli/plasmo/src/commands/build.ts
cli/plasmo/src/commands/dev.ts

This logs the `--target` when running `plasmo build` or `plasmo dev`, making it easy to see at a glance what browser target you are building for.
This can help to avoid surprises and confusion if the thing you think is getting built isn't getting built!

feat: log the target when running `plasmo build` or `plasmo dev`

---

cli/plasmo/src/features/manifest-factory/base.ts

Add `overrides` key to manifest to allow setting browser-specific manifest key-values, using just a dumb shallow-merge.
I personally needed this feature because Firefox CSP automatically upgrades HTTP connections to HTTPS, but setting anything else broke functionality in Safari.
Related PRs:
* https://github.com/PlasmoHQ/examples/pull/67
* https://github.com/PlasmoHQ/plasmo-constants/pull/2
- (OPTIONAL) Discord ID: tbrockman

Add 'overrides' key for browser-specific manifest settings

---

cli/plasmo/src/features/helpers/flag.ts

Unlike many CLIs, the `plasmo` CLI requires argument values to be provided with `=` notation (e.g. `--target=chrome-mv3`).
This requirement comes from the `getFlag` method in the `@plasmo/utils` package.
https://github.com/PlasmoHQ/plasmo-utils/blob/2838ca6214117bfd93b566b4b75586f6a9bd89f7/flags.ts#L8-L16
This expectation isn't clear in the documentation in the CLI, which is quite misleading. This fixes that, updating all of the examples to clearly show setting a value with `=`.

fix(docs): clarify in the CLI help that argument values must be specified with `=`

---

.github/workflows/test-examples.yml
cli/plasmo/src/features/manifest-factory/base.ts
package.json
pnpm-lock.yaml

Fixes an issue with `overrides` key not being deleted when the browser target _doesn't_ match 😳
Adds testing in [`examples/with-browser-specific-overrides`](https://github.com/PlasmoHQ/examples/pull/68/files) to verify manifest.json is produced as expected, which should probably be merged before this PR (and then this one can be updated with the new ref).
Adds test runs to CI (I think).

Fix deletion of `output.overrides`

---

cli/plasmo/src/commands/build.ts
cli/plasmo/src/commands/dev.ts
cli/plasmo/src/commands/package.ts

#1081
This PR addresses an issue with the checkNewVersion function. Currently, checkNewVersion is using await, which causes both the dev and build commands to wait until checkNewVersion finishes executing. This results in a delay before these commands can start, affecting the overall developer experience.
- [ x] I agree to follow this project's [Code of Conduct](https://github.com/PlasmoHQ/plasmo/blob/main/.github/CODE_OF_CONDUCT.md)
- [x ] I agree to license this contribution under the MIT LICENSE
- [x ] I checked the [current PR](https://github.com/PlasmoHQ/plasmo/pulls) for duplication.
- (OPTIONAL) Discord ID: 

fix: checkNewVersion Blocks dev and build Commands

---

cli/plasmo/src/features/env/env-config.ts
cli/plasmo/src/features/helpers/create-parcel-bundler.ts

So that variables like `PLASMO_BROWSER` are accessible in downstream Parcel plugins via `process.env`.

Set bundle config as internal environment variables

---

cli/plasmo/src/features/background-service-worker/bgsw-messaging.ts

Fixes a build error that occurs when a custom .babelrc is provided in the project that makes use of `@babel/preset-env`.
If you have a .babelrc and an external message such as `src/background/messages/external/Test.ts`, you will receive the following trying to build the extension:
```
Identifier 'messagesExternalTest' has already been declared. (38:20)
```
In `cli/plasmo/src/features/background-service-worker/bgsw-messaging.ts`'s `getHandlerList` function, it performs a glob of all typescript files that are within the designated messages folder. Due to `messages/external` (public external messaging) being contained within `messages` (extension internal messaging), this causes any external messaging to have a duplicate import created during build when `getHandlerList` is invoked with …

bug: Ignore external folder when globbing messages folder

---

cli/plasmo/src/commands/dev.ts
cli/plasmo/src/features/helpers/loading-animation.ts
core/parcel-core/src/index.ts

This PR enhances the build process feedback by implementing a loading animation in the terminal. It addresses the issue of unclear build status during development, especially for longer builds or multiple hot reloads.
Specifically, this PR:
- Adds a loading animation at the start of each build/hot reload process
- Removes the animation when the build completes (success or failure)
- Improves visibility of the current build status
This change aims to solve the problem described in issue #1117, where it was difficult to determine if a build was in progress or completed, especially after multiple hot reloads.
I'm open to any feedback or suggestions for improvement. If you have any questions or if there's anything you'd like me to modify, please leave a comment. …

feat: add build loading awareness in the terminal(#1117)

---

core/parcel-runtime/src/utils/loading-indicator.ts

Last June, [this PR](https://github.com/PlasmoHQ/plasmo/pull/1000) was created to fix a bug in the Loading Indicator which caused it to break on some websites (e.g. LinkedIn) because the newly-created trusted-type was not valid per the site's CSP for `trusted-types`. For example, if you run the following on LinkedIn:
```
document.querySelector('meta[name="trusted-types"]')
```
You get this `meta` tag:
```
<meta name="trusted-types" content="require-trusted-types-for 'script'; trusted-types default jSecure 'allow-duplicates' dompurify;" data-sanitizer="RegExp" data-pattern="<" data-replacement="&amp;lt;" data-report-to="/security/csp?a=web">
```
The `trusted-types` of which notably do not include the policy which was previously being created by default in `loading-indicator.ts` - …

fix: semicolon bugfix for TrustedTypePolicy Creation in Loading Indicator

---

.github/workflows/test-examples.yml
core/parcel-core/src/index.ts

This PR makes sure the CI fails if a package fails to build. Currently, we are seeing examples fail to build, but the CI passes anyway 👎 

chore: fail CI if 'pnpm run build:examples' fails

---

.gitmodules

This PR replaces all .gitmodule entries with HTTPS urls instead of SSH urls. This is because there is an [issue with Renovate](https://github.com/renovatebot/renovate/discussions/34113) when cloning submodules using ssh, even if they're public.

chore: replace ssh urls with https urls in .gitmodules

---

cli/plasmo/src/features/project-creator/git-init.ts
cli/plasmo/src/features/project-creator/index.ts

Checking `error.errno` can vary across OSes and Node.js versions ((it might be numeric on some systems and string on others). Using `error.code === "ENOENT"` is more consistent and ensures we correctly handle "command not found" errors in a cross-platform way.
Also potentially relates to [issue](https://github.com/PlasmoHQ/plasmo/issues/1160)
- (OPTIONAL) Discord ID: alexb25

fix: use error.code instead of error.errno for ENOENT handling

---

cli/plasmo/README.md
cli/plasmo/i18n/README.de-DE.md
cli/plasmo/i18n/README.fr-FR.md
cli/plasmo/i18n/README.id-ID.md
cli/plasmo/i18n/README.ja-JP.md
cli/plasmo/i18n/README.ko-KR.md
cli/plasmo/i18n/README.ru-RU.md
cli/plasmo/i18n/README.tr-TR.md
cli/plasmo/i18n/README.vi-VN.md
cli/plasmo/i18n/README.zh-CN.md

The link to the Code of Conduct was set as `./.github/CODE_OF_CONDUCT.md`, which incorrectly pointed to locations such as `https://github.com/PlasmoHQ/plasmo/blob/main/.github/.github/CODE_OF_CONDUCT.md` and `https://github.com/PlasmoHQ/plasmo/blob/main/cli/plasmo/.github/CODE_OF_CONDUCT.md`. In the i18n version, it pointed to `https://github.com/PlasmoHQ/plasmo/blob/main/cli/plasmo/i18n/.github/CODE_OF_CONDUCT.md`, all of which were incorrect. I corrected the link to use an absolute path, similar to the contributing guidelines. 
Additionally, in the Russian version, there was no mention of the Code of Conduct, so I added the relevant content.
To join the server, visit: …

Fix broken links in readme

---

cli/plasmo/src/features/extension-devtools/git-ignore.ts
packages/init/templates/README.md

- This PR fixes a broken link (`https://bpp.browser.market`) to the correct one (`https://github.com/marketplace/actions/browser-platform-publisher`).
- close #1219 

Fix the bpp link to the correct one

---

cli/plasmo/templates/static/common/csui.ts

This PR fixes unmounting of components when the anchor no longer exists.
Since the anchor wasn't checked, components would stack up on top of each other as the anchor disappears and reappears in the DOM from user interactions.
Also added `el.remove()` to remove the empty `plasmo-csui` elements and clean up the DOM.
Fixes https://github.com/PlasmoHQ/plasmo/issues/551
- Discord ID: cheesestringer

fix: trigger unmount when the anchor no longer exists
