cli/plasmo/src/features/extension-devtools/plasmo-extension-manifest.ts
=> feat: add ability to inject env to content-script

cli/plasmo/package.json, cli/plasmo/templates/plasmo.d.ts
=> feat: add url scheme

cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/content-script.ts, cli/plasmo/src/features/extension-devtools/parse-ast.ts, pnpm-lock.yaml
=> fix: implement own AST parser to reduce dep

cli/plasmo/src/commands/init.ts
=> fix(cli): using cwd for init

cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/plasmo-extension-manifest.ts, cli/plasmo/src/features/extension-devtools/scaffolds.ts
=> fix: using content.tsx at project root

cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/package-file.ts, cli/plasmo/src/features/extension-devtools/plasmo-extension-manifest.ts
=> feat: copy web accessible resources from node_modules

.github/CONTRIBUTING.md, .github/workflows/test-examples.yml, cli/create-plasmo/package.json, cli/create-plasmo/src/index.ts, cli/plasmo/package.json, cli/plasmo/src/commands/init.ts, cli/plasmo/src/features/extension-devtools/ensure-manifest.ts, cli/plasmo/src/features/extension-devtools/package-file.ts, cli/plasmo/src/features/extension-devtools/plasmo-extension-manifest.ts, pnpm-lock.yaml
=> chore: refine war resolver

cli/plasmo/package.json, cli/plasmo/templates/static/content-script-ui-mount.tsx, pnpm-lock.yaml
=> feat: add id to csui containers

cli/plasmo/src/features/manifest-factory/base.ts
=> fix: content-script override 

cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/generate-icons.ts
=> feat: use smaller icon if available

cli/plasmo/src/commands/init.ts
=> fix: ignore install error

cli/plasmo/templates/static/react17/content-script-ui-mount.tsx, cli/plasmo/templates/static/react18/content-script-ui-mount.tsx, cli/plasmo/templates/static/svelte3/content-script-ui-mount.ts, cli/plasmo/templates/static/vue3/content-script-ui-mount.ts
=> feat: support users defining a `getShadowHostId` async function in content-script

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/project-path.ts, cli/plasmo/src/features/extension-devtools/project-watcher.ts, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/src/features/manifest-factory/create-manifest.ts, cli/plasmo/src/features/manifest-factory/scaffolder.ts
=> feat: support html override, fix nested csui import

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/project-path.ts, cli/plasmo/src/features/extension-devtools/project-watcher.ts, cli/plasmo/src/features/helpers/path.ts, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/src/features/manifest-factory/create-manifest.ts, cli/plasmo/src/features/manifest-factory/mv2.ts, cli/plasmo/src/features/manifest-factory/mv3.ts, cli/plasmo/src/features/manifest-factory/scaffolder.ts
=> feat: target specific entry files

cli/plasmo/src/features/extension-devtools/project-path.ts
Signed-off-by: Christopher Dieringer <cdaringe@users.noreply.github.com>
background resolution is not working, no scripts are found
Correct path resolution
=> fix: correct background script entry resolution

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/commands/build.ts, cli/plasmo/src/commands/dev.ts, cli/plasmo/src/features/extension-devtools/get-target-data.ts, cli/plasmo/src/features/extension-devtools/load-env-config.ts, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/src/features/manifest-factory/create-manifest.ts, cli/plasmo/templates/plasmo.d.ts
=> feat: expose target data to env

packages/parcel-config/index.json, packages/parcel-config/package.json, packages/parcel-resolver/src/handle-remote-caching.ts, packages/parcel-resolver/src/handle-tilde-src.ts, packages/parcel-resolver/src/index.ts, packages/parcel-transformer-inject-env/.gitignore, packages/parcel-transformer-inject-env/package.json, packages/parcel-transformer-inject-env/src/index.ts, packages/parcel-transformer-inject-env/tsconfig.json, pnpm-lock.yaml
=> feat: add data-env and raw-env

cli/plasmo/i18n/README.de-DE.md, cli/plasmo/i18n/README.vi-VN.md, cli/plasmo/i18n/README.zh-CN.md, cli/plasmo/readme.md
As requested in your last demo, this PR adds a german translation of the README.
=> Add german README translation

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/index.json, packages/parcel-config/package.json, packages/parcel-packager/package.json, packages/parcel-packager/src/index.ts, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/handle-declarative-net-request.ts
=> fix: wrong mv2 check in packager

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/manifest-factory/ui-library.ts
=> fix: major version coerce instead of parsing

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/manifest-factory/mv2.ts
=> fix: convert mv3 csp to mv2 csp

cli/plasmo/package.json, cli/plasmo/templates/plasmo.d.ts
=> fix: add typing for new schemes

cli/plasmo/templates/static/react18/index.tsx
=> fix: add explicit react dependency import in template

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/src/features/manifest-factory/create-manifest.ts, cli/plasmo/src/features/manifest-factory/mv2.ts, cli/plasmo/src/features/manifest-factory/mv3.ts, cli/plasmo/src/features/manifest-factory/scaffolder.ts, cli/plasmo/templates/static/react17/index.html, cli/plasmo/templates/static/react18/index.html, cli/plasmo/templates/static/svelte3/index.html, cli/plasmo/templates/static/vue3/index.html, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/handle-deep-loc.ts
=> feat: adding stable name for all html pages

cli/plasmo/src/features/extension-devtools/load-env-config.ts, cli/plasmo/templates/plasmo.d.ts
=> feat: adding NODE_ENV to public env

cli/plasmo/src/features/extension-devtools/package-file.ts, cli/plasmo/src/features/extension-devtools/project-creator.ts, cli/plasmo/src/features/manifest-factory/base.ts
- This PR also include BSS sanitization code
=> fix: add proper package names to the generated project

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/type.ts, cli/plasmo/templates/static/react17/content-script-ui-mount.tsx, cli/plasmo/templates/static/react18/content-script-ui-mount.tsx, cli/plasmo/templates/static/svelte3/content-script-ui-mount.ts, cli/plasmo/templates/static/vue3/content-script-ui-mount.ts, cli/plasmo/tsconfig.json, package.json
=> feat: csui inline mount with observer

cli/plasmo/src/features/extension-devtools/package-file.ts, cli/plasmo/src/features/extension-devtools/project-creator.ts
=> fix: add version when initializing with example

cli/plasmo/i18n/README.de-DE.md, cli/plasmo/i18n/README.fr-FR.md, cli/plasmo/i18n/README.vi-VN.md, cli/plasmo/i18n/README.zh-CN.md, cli/plasmo/readme.md
=> feat: add french README translation

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/generate-icons.ts, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/src/features/manifest-factory/mv2.ts, cli/plasmo/src/features/manifest-factory/mv3.ts
=> fix: icon development resolution, add retina support

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/templates/static/react17/content-script-ui-mount.tsx, cli/plasmo/templates/static/react18/content-script-ui-mount.tsx
=> feat: use shadow host id lookup if available

cli/plasmo/src/features/manifest-factory/base.ts
=> fix: web accessible resource resolution

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/type.ts, cli/plasmo/templates/static/react17/content-script-ui-mount.tsx, cli/plasmo/templates/static/react18/content-script-ui-mount.tsx, cli/plasmo/templates/static/svelte3/content-script-ui-mount.ts, cli/plasmo/templates/static/vue3/content-script-ui-mount.ts
=> fix: injecting Svelte CSUI to SPA DOM

.vscode/settings.json, cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/content-script-config.ts, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/templates/static/react17/content-script-ui-mount.tsx, cli/plasmo/templates/static/react18/content-script-ui-mount.tsx, cli/plasmo/templates/static/svelte3/content-script-ui-mount.ts, cli/plasmo/templates/static/vue3/content-script-ui-mount.ts, package.json, packages/parcel-resolver/package.json, packages/parcel-transformer-vue3/package.json, pnpm-lock.yaml
=> feat: remove onload csui, fix svelte + vue mounts

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/package.json, packages/parcel-packager/package.json, packages/parcel-packager/src/get-web-accessible-resources.ts
=> fix: wars for mv3 not include original wars

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/manifest-factory/create-manifest.ts, packages/parcel-config/package.json, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/handle-deep-loc.ts
=> fix: mv2 background scripts loading

cli/plasmo/src/features/manifest-factory/scaffolder.ts, cli/plasmo/src/features/project-creator/index.ts, cli/plasmo/tsconfig.json
=> chore: slight refactor

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/package.json, packages/parcel-packager/package.json, packages/parcel-packager/src/get-web-accessible-resources.ts, packages/parcel-runtime/package.json, packages/parcel-runtime/src/index.ts, packages/parcel-runtime/src/runtimes/0-patch-module.ts, packages/parcel-runtime/src/runtimes/background-service-runtime.ts, packages/parcel-runtime/src/runtimes/hmr-check.ts, packages/parcel-runtime/src/runtimes/hmr-utils.ts, packages/parcel-runtime/src/runtimes/inject-socket.ts, packages/parcel-runtime/src/runtimes/page-runtime.ts, packages/parcel-runtime/src/runtimes/script-runtime.ts, packages/parcel-runtime/src/types.ts
=> fix: HMR with live-reload fallback + script runtime deps check

packages/init/bpp.yml, packages/init/package.json
=> chore: bump init bpp to v3

cli/plasmo/src/features/extension-devtools/get-bundle-config.ts, cli/plasmo/src/features/extension-devtools/load-env-config.ts, cli/plasmo/src/features/helpers/flag.ts
=> feat: add more flexibility to env configuration

cli/plasmo/templates/plasmo.d.ts
Signed-off-by: Aliaksei Kislou <evenfrosty@gmail.com>
This adds the missing PostCSS file extension to the type definitions.
=> Avoid TS compiler errors for PostCSS files

cli/plasmo/src/features/manifest-factory/base.ts
Context: https://discord.com/channels/946290204443025438/1039453152941977670
This will fix the issue when web accessible resource throwing error if the specified resource does not exist (this is allowed as developer can actually write virtual resource with bgsw)
=> fix: await for WAR check

cli/plasmo/src/commands/dev.ts
The parcel trace log might be a bit too much when working. We're moving it to a verbose log instead.
=> chore: put parcel trace log to verbose

cli/plasmo/templates/static/common/csui.ts, cli/plasmo/templates/static/react17/content-script-ui-mount.tsx, cli/plasmo/templates/static/react18/content-script-ui-mount.tsx, cli/plasmo/templates/static/svelte3/content-script-ui-mount.ts, cli/plasmo/templates/static/vue3/content-script-ui-mount.ts
=> fix: CSUI anchor observer on document start

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/package.json, packages/parcel-resolver/index.mjs, packages/parcel-resolver/package.json, packages/parcel-resolver/tsup.config.ts, pnpm-lock.yaml
=> fix: node polyfill bundling for browser target 

cli/plasmo/README.md
Signed-off-by: 荣顶 <wangrongding@qq.com>
=> chore: update README.md

packages/parcel-transformer-svelte3/package.json, packages/parcel-transformer-svelte3/src/index.ts
adds `svelte.config.cjs` to the supported list of config files plasmo attempts to read from, fixes #365
=> fix: support reading svelte.config.cjs, ref #365

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/background-service-worker/bgsw-entry.ts, cli/plasmo/src/features/background-service-worker/bgsw-messaging-declaration.ts, cli/plasmo/src/features/background-service-worker/bgsw-messaging.ts
=> fix: messaging API init

cli/plasmo/src/features/extension-devtools/project-path.ts
Additional changes for #363, which miss the `background.js`
=> feat: supports js extension for background

cli/plasmo/src/features/extension-devtools/project-path.ts
In addition to #368 and #363 , supports `content.js` and `sandbox.js`
=> feat: supports js extension for content and sandbox

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/background-service-worker/bgsw-entry.ts, cli/plasmo/src/features/background-service-worker/bgsw-messaging-declaration.ts, cli/plasmo/src/features/background-service-worker/update-bgsw-entry.ts, pnpm-lock.yaml
=> feat: use json5

packages/parcel-config/package.json, packages/parcel-runtime/package.json, packages/parcel-runtime/src/index.ts, packages/parcel-runtime/src/runtimes/page-runtime.ts, packages/parcel-runtime/src/types.ts, packages/parcel-runtime/src/utils/inject-socket.ts
This PR fix Parcel's config parser trying to traverse all the way to project root.
=> fix: reading package.json in monorepo setup

cli/plasmo/src/commands/build.ts, cli/plasmo/src/commands/dev.ts, cli/plasmo/src/features/helpers/create-parcel-bundler.ts, cli/plasmo/src/features/manifest-factory/base.ts, packages/parcel-transformer-manifest/src/index.ts
=> fix: inline source map for prod

cli/plasmo/README.md
Adding links and adding plural for examples
=> chore: improve README contributing section

cli/plasmo/README.md
We received some feedback on hacker news asking us to add supported browsers.
=> Update README to add supported browsers link

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/src/features/manifest-factory/scaffolder.ts
=> fix: tab pages html override

packages/messaging/package.json, packages/messaging/src/hook.ts
=> fix: messaging port API binding, with more elaborate example

cli/plasmo/src/features/extension-devtools/package-file.ts, cli/plasmo/src/features/helpers/prompt.ts, cli/plasmo/src/features/project-creator/from-existing-manifest.ts, cli/plasmo/src/features/project-creator/get-raw-name.ts, cli/plasmo/src/features/project-creator/index.ts
=> fix: adding more prompt for other basic metadata

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/background-service-worker/bgsw-messaging-declaration.ts, packages/messaging/package.json, packages/messaging/src/background.ts, packages/messaging/src/hook.ts, packages/messaging/src/index.ts, packages/messaging/src/port.ts, packages/messaging/src/utils.ts
=> fix(messaging): port name typing

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/package.json, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/csp-patch-hmr.ts
=> fix(manifest-transformer): csp generator

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/generate-icons.ts, packages/messaging/package.json, packages/messaging/src/relay.ts
=> fix: copy icon buffer instead of reuse them

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/manifest-factory/base.ts
=> fix: wrong page path when using src-path

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/package.json, packages/parcel-runtime/package.json, packages/parcel-runtime/src/runtimes/script-runtime.ts
=> fix(parcel-runtime): try catch port init when injecting main world script

cli/plasmo/src/features/helpers/traverse.ts, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/src/features/manifest-factory/mv2.ts
=> fix(cli): prune key on empty object

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/manifest-factory/base.ts
=> fix(cli): pass down all options UI stuff

packages/parcel-config/package.json, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/handle-background.ts
=> fix(transformer-manifest): handle firefox bgsw issue

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/messaging/package.json, packages/messaging/src/hook.ts, packages/messaging/src/index.ts, packages/messaging/src/types.ts, packages/parcel-config/package.json, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/handle-background.ts
=> feat(messaging): useMessage hook simplified to be message receiver

cli/plasmo/src/features/manifest-factory/mv3.ts, packages/messaging/package.json, packages/messaging/src/types.ts, pnpm-lock.yaml
=> fix(messaging): pass down generic types

cli/plasmo/src/features/project-creator/index.ts
=> feat(storage): namespace + secure storage password migration

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/commands/build.ts
=> feat: plasmo build --no-minify

cli/plasmo/README.md, cli/plasmo/i18n/README.ru-RU.md
=> chore: translate readme to russian

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/package.json, packages/parcel-resolver-post/package.json, packages/parcel-resolver-post/src/handle-ts-path.ts
=> fix: ts resolver for svelte and vue

cli/plasmo/README.md, cli/plasmo/i18n/README.tr-TR.md
add turkish README translation, README.tr-TR.md
=> feat: add turkish README translation

packages/parcel-config/package.json, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/handle-background.ts
=> fix(parcel-transformer-manifest): firefox bgsw handling

cli/plasmo/src/features/env/env-config.ts
=> feat(cli): pass down system env when parsing

packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/schema.ts
=> fix: manifest transformer add commands global

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/index.json, packages/parcel-config/package.json, packages/parcel-optimizer-encapsulate/.gitignore, packages/parcel-optimizer-encapsulate/package.json, packages/parcel-optimizer-encapsulate/src/index.ts, packages/parcel-optimizer-encapsulate/tsconfig.json, packages/parcel-optimizer-encapsulate/tsup.config.ts, packages/parcel-optimizer-es/src/index.ts, pnpm-lock.yaml
This PR encapsulate parcel's amd define, enabling CS to work on site such as https://dsf.sharefile.com/Authentication/Login
=> fix: define encapsulation, enabling CS to work on site that use require

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/templates/plasmo.d.ts, packages/parcel-config/index.json, packages/parcel-config/package.json
=> fix: svg react with proper type and inline style

packages/parcel-runtime/src/runtimes/script-runtime.ts
=> fix: undefined chrome global

cli/plasmo/README.md, cli/plasmo/i18n/README.de-DE.md, cli/plasmo/i18n/README.fr-FR.md, cli/plasmo/i18n/README.id-ID.md, cli/plasmo/i18n/README.ja-JP.md, cli/plasmo/i18n/README.ru-RU.md, cli/plasmo/i18n/README.tr-TR.md, cli/plasmo/i18n/README.vi-VN.md, cli/plasmo/i18n/README.zh-CN.md
This PR adds Japanese README translation, REAME.ja-JP.md. Also, it updates the links to other languages' README in each README file.
- Discord ID: Risu#1380
=> feat: add Japanese README translation

cli/plasmo/src/features/background-service-worker/bgsw-main-world-script.ts
This PR ensure mainworld injection will not throw `srcContentInject` error when the bgsw refresh and try to re-inject the mainworld script again.
=> fix: Wrap main world registration inside a try/catch

cli/plasmo/i18n/README.zh-CN.md
This PR is to update the Simplified Chinese version of the README which hasn't been updated for a long time and has some missing content.
- Discord ID: nozomi#4945
=> doc: update zh-CN README translation

packages/messaging/src/index.ts
Correct typo in plasma messaging package
This PR ...
- (OPTIONAL) Discord ID: chmex.eth#4215
=> Correct typo in messaging package - Update index.ts

packages/messaging/package.json, packages/messaging/src/hook.ts, packages/messaging/src/message.ts, packages/messaging/src/port.ts
This PR ...
- (OPTIONAL) Discord ID: louisy#6856
=> feat: add port reconnection mechanism

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/commands/build.ts, cli/plasmo/src/features/helpers/create-parcel-bundler.ts, cli/plasmo/tsconfig.json, packages/parcel-bundler/package.json, packages/parcel-bundler/src/bit-set.ts, packages/parcel-bundler/src/create-bundle.ts, packages/parcel-bundler/src/create-ideal-graph.ts, packages/parcel-bundler/src/decorate-legacy-graph.ts, packages/parcel-bundler/src/types.ts, packages/parcel-config/package.json, packages/parcel-optimizer-encapsulate/package.json, packages/parcel-optimizer-encapsulate/tsconfig.json, packages/parcel-optimizer-es/package.json, packages/parcel-optimizer-es/src/index.ts, packages/parcel-optimizer-es/tsconfig.json, packages/parcel-runtime/package.json, packages/parcel-runtime/src/index.ts, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/handle-background.ts, packages/parcel-transformer-manifest/tsconfig.json, pnpm-lock.yaml
=> feat: better optimizer based on upstream swc

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/extension-devtools/content-script-config.ts, cli/plasmo/src/features/helpers/create-parcel-bundler.ts, cli/plasmo/src/features/manifest-factory/base.ts, packages/parcel-config/package.json, packages/parcel-runtime/package.json, packages/parcel-runtime/src/index.ts, packages/parcel-runtime/tsconfig.json
=> feat: --no-cs-reload

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/package.json, packages/parcel-runtime/package.json, packages/parcel-runtime/src/runtimes/background-service-runtime.ts, packages/parcel-runtime/src/runtimes/script-runtime.ts, packages/persistent/package.json, packages/persistent/src/background.ts, pnpm-lock.yaml
This PR closes #370 
ref: https://developer.chrome.com/docs/extensions/mv3/service_workers/service-worker-lifecycle/#idle-shutdown
=> feat: persistent runtime and make dev runtime more resilient

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/features/manifest-factory/base.ts, cli/plasmo/templates/plasmo.d.ts, cli/plasmo/tsconfig.json, packages/parcel-config/package.json, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/handle-background.ts, packages/parcel-transformer-manifest/src/handle-sandboxes.ts, packages/parcel-transformer-manifest/tsconfig.json, pnpm-lock.yaml
=> fix: properly handle firefox dev bgsw, remove sandbox for firefox

cli/create-plasmo/package.json, cli/plasmo/package.json, packages/parcel-config/package.json, packages/parcel-transformer-manifest/package.json, packages/parcel-transformer-manifest/src/csp-patch-hmr.ts, packages/parcel-transformer-manifest/src/handle-background.ts
=> fix: firefox bgsw bundling and csp

cli/create-plasmo/package.json, cli/plasmo/package.json, cli/plasmo/src/type.ts, cli/plasmo/templates/static/common/csui-container-react.tsx, cli/plasmo/templates/static/common/csui-container-vanilla.tsx, cli/plasmo/templates/static/common/csui.ts, cli/plasmo/templates/static/react17/content-script-ui-mount.tsx, cli/plasmo/templates/static/react18/content-script-ui-mount.tsx
=> feat: improve CSUI overlay repositioning

packages/messaging/package.json, packages/messaging/src/pub-sub.ts
- Requires "externally_connectable" in manifest.json
This PR ...
- (OPTIONAL) Discord ID: cyberwomble
=> feat: create pub/sub abstraction

cli/plasmo/src/commands/package.ts, cli/plasmo/src/features/extra/cache-busting.ts, cli/plasmo/src/features/manifest-factory/zip.ts
=> feat: strip out source maps from zip bundle

cli/create-plasmo/package.json, cli/plasmo/package.json, core/parcel-config/package.json, core/parcel-transformer-manifest/package.json, core/parcel-transformer-manifest/src/handle-background.ts
=> fix: firefox script handling

api/messaging/package.json, api/persistent/package.json, api/selector/package.json, cli/create-plasmo/package.json, cli/plasmo/package.json, core/parcel-bundler/package.json, core/parcel-compressor-utf8/package.json, core/parcel-config/package.json, core/parcel-core/package.json, core/parcel-namer-manifest/package.json, core/parcel-optimizer-encapsulate/package.json, core/parcel-optimizer-es/package.json, core/parcel-packager/package.json, core/parcel-resolver-post/package.json, core/parcel-resolver-post/src/handle-hacks.ts, core/parcel-resolver-post/src/handle-module-exports.ts, core/parcel-resolver/package.json, core/parcel-runtime/package.json, core/parcel-transformer-inject-env/package.json, core/parcel-transformer-inline-css/package.json, core/parcel-transformer-lab/package.json, core/parcel-transformer-manifest/package.json, core/parcel-transformer-svelte/package.json, core/parcel-transformer-vue/package.json, package.json, pnpm-lock.yaml
=> chore: bump dependencies

cli/plasmo/README.md, cli/plasmo/i18n/README.de-DE.md, cli/plasmo/i18n/README.fr-FR.md, cli/plasmo/i18n/README.id-ID.md, cli/plasmo/i18n/README.ja-JP.md, cli/plasmo/i18n/README.ko-KR.md, cli/plasmo/i18n/README.ru-RU.md, cli/plasmo/i18n/README.tr-TR.md, cli/plasmo/i18n/README.vi-VN.md, cli/plasmo/i18n/README.zh-CN.md
This PR adds a Korean README and adds Korean links to other README files.
And I fixed a typo in the Russian README. ebf021f
- Discord ID: 강주혁#6010
=> docs: add korean README translation

api/messaging/package.json, api/persistent/package.json, api/selector/package.json, cli/create-plasmo/package.json, cli/plasmo/package.json
This PR adds the `directory` to the `repository` field in the published package.json. This makes sure that the link on npm is correct.
- Discord ID: 380325824286687233
=> chore: Add directory to repository field in package.json

cli/plasmo/templates/static/common/vue.ts
fix built crx runtime error when use vue@3.4
=> fix(vue): support new vue compile-time-flags

.vscode/settings.json, core/parcel-config/package.json, core/parcel-resolver-post/package.json, core/parcel-resolver-post/src/handle-ts-path.ts, core/parcel-resolver/package.json, core/parcel-resolver/src/handle-tilde-src.ts, core/parcel-transformer-inline-css/package.json, core/parcel-transformer-inline-css/src/index.ts, core/parcel-transformer-manifest/package.json, core/parcel-transformer-manifest/src/handle-background.ts, core/parcel-transformer-manifest/src/index.ts, package.json, pnpm-lock.yaml
=> fix: resolver in general

core/parcel-runtime/src/runtimes/script-runtime.ts
Fix a citation link from a link to a permalink
- (OPTIONAL) Discord ID: 395165536545275905
=> fix: citation - use permalink

core/parcel-transformer-manifest/src/schema.ts
=> fix: Fixes missing schema definition in mv3 for match_origin_as_fallback

cli/create-plasmo/package.json, cli/plasmo/package.json, core/parcel-config/package.json, core/parcel-resolver-post/package.json, core/parcel-resolver-post/src/handle-module-exports.ts, core/parcel-resolver-post/src/index.ts
=> fix: resolve all ESM module if possible

cli/create-plasmo/package.json, cli/plasmo/package.json, core/parcel-config/package.json, core/parcel-resolver/package.json, core/parcel-resolver/src/handle-absolute-root.ts, core/parcel-resolver/src/handle-tilde-src.ts, core/parcel-resolver/src/shared.ts
=> fix: absolute resolver with stats check

cli/plasmo/src/features/extension-devtools/project-watcher.ts, cli/plasmo/src/features/manifest-factory/scaffolder.ts, core/parcel-bundler/src/create-ideal-graph.ts, core/parcel-core/src/resolve-options.ts
=> chore: fix some typos in comments

.github/CONTRIBUTING.md
This PR fixes #1121.
- (OPTIONAL) Discord ID: magicwan
=> doc: fix Contributing.md's pnpm installation instructions

cli/plasmo/package.json, package.json, pnpm-lock.yaml
This PR:
- Removes ``sharp`` from the core ``package.json``
- Upgrades ``sharp`` from ``0.32.6`` to ``0.33.5``
=> chore: upgrade sharp from 0.32.6 to 0.33.5

renovate.json
This PR groups all @parcel packages into a single renovate PR.
=> Update renovate.json to group @parcel packages

cli/plasmo/src/features/helpers/flag.ts
Small nit to add missing documentation for the `--no-cs-reload` flag related to this [feat](https://github.com/PlasmoHQ/plasmo/pull/597), might be useful for everyone that complains about the "invalidated context"
=> doc: add documentation for --no-cs-reload flag

renovate.json
=> chore: add group:allNonMajor to renovate.json
